- name: Create upstash service
  template:
    src: upstash-redis-local.service.j2
    dest: /etc/systemd/system/upstash-redis-local.service
    mode: "0644"

- name: Start upstash service
  ansible.builtin.service:
    name: upstash-redis-local
    state: started
    enabled: true

- name: Check if upstash-redis-local is active
  command: systemctl is-active upstash-redis-local
  register: upstash_status
  changed_when: false
  failed_when: upstash_status.stdout != "active"