receivers:
  docker_stats:
    endpoint: unix:///var/run/docker.sock
    metrics:
      container.cpu.utilization:
        enabled: true
      container.memory.percent:
        enabled: true
      container.network.io.usage.rx_bytes:
        enabled: true
      container.network.io.usage.tx_bytes:
        enabled: true
      container.network.io.usage.rx_dropped:
        enabled: true
      container.network.io.usage.tx_dropped:
        enabled: true
      container.memory.usage.limit:
        enabled: true
      container.memory.usage.total:
        enabled: true
      container.blockio.io_service_bytes_recursive:
        enabled: true

  postgresql:
    endpoint: "${DB_ENDPOINT}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    databases: "${DB_NAME}"
    collection_interval: 10s
    tls:
      insecure: true
      insecure_skip_verify:
        true  

  redis:
    endpoint: "${REDIS_ENDPOINT}"
    collection_interval: 10s

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
  resourcedetection/env:
    detectors: [env]
    timeout: 2s
    override: false
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["dns", "os"]
  resourcedetection/docker:
    detectors: [env, docker]
    timeout: 2s
    override: false

exporters:
  splunk_hec/metrics:
    token: "${SPLUNK_HEC_TOKEN}"
    endpoint: "${SPLUNK_HEC_URL}"
    index: docker_metrics
    source: "otel"
    sourcetype: "otel"
    tls:
      insecure_skip_verify: true


service:
  pipelines:
    metrics:
      receivers: [docker_stats, postgresql, redis]
      processors: [resourcedetection/env, resourcedetection/system, resourcedetection/docker, batch]
      exporters: [splunk_hec/metrics]
