- name: Change configuration Splunk HEC
  template:  
    src: splunk-otel-collector.conf.j2 
    dest: "{{ otel_work_dir }}/splunk-otel-collector.conf"
    owner: splunk-otel-collector
    group: splunk-otel-collector
    mode: "0600"

- name: Change agent configuration
  template:  
    src: agent_config.yaml.j2
    dest: "{{ otel_work_dir }}/agent_config.yaml"
    owner: splunk-otel-collector
    group: splunk-otel-collector
    mode: "0755"
