- name: Create opentelemetry dir
  file:
    path: "{{ otel_dir }}"
    state: directory
    mode: '0755'

- name: Get deb pkg
  get_url:
    url: "{{ otel_download }}"
    dest: "{{ otel_dir }}"
    mode: "0644"

- name: Install opentelemetry
  ansible.builtin.apt:
    deb: "/home/vagrant/{{ otel_dir }}/{{ otel_pkg }}"
