name: Jira docker

x-app-base: &app-base
  image: jira-clone:latest
  environment:
    DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@jira_db:5432/${DATABASE_NAME}
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
    UPSTASH_REDIS_REST_URL: "http://redis_proxy:8000"
    UPSTASH_REDIS_REST_TOKEN: ${UPSTASH_REDIS_REST_TOKEN}
  depends_on:
    jira_db:
      condition: service_healthy
    redis_proxy:
      condition: service_started
  logging:
    driver: "json-file"
    options:
      tag: "{{.Name}}/{{.ID}}"

services:
  jira_db:
    image: postgres:latest
    hostname: jira_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - jira_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}/{{.ID}}"

  migrate:
    image: jira-clone-migrate:latest
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@jira_db:5432/${DATABASE_NAME}
    depends_on:
      jira_db:
        condition: service_healthy
    restart: "no"
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}/{{.ID}}"

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    hostname: redis
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}/{{.ID}}"

  redis_proxy:
    image: upstash-local:latest
    environment:
      UPSTASH_TOKEN: ${UPSTASH_REDIS_REST_TOKEN}
      SERVER_ADDRESS: ":8000"
      REDIS_ADDRESS: "redis:6379"
    depends_on:
      - redis
    hostname: redis_proxy
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}/{{.ID}}"
    

  app1:
    <<: *app-base
    hostname: app1


  app2:
    <<: *app-base
    hostname: app2


  nginx:
    image: nginx:alpine-otel
    expose:
      - 8080
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}/{{.ID}}"
    hostname: nginx

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    user: "0"
    expose:
      - "4317"
      - "4318"
    environment:
      DB_ENDPOINT: jira_db:5432
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      REDIS_ENDPOINT: redis:6379
      SPLUNK_HEC_TOKEN: ${SPLUNK_HEC_TOKEN}
      SPLUNK_HEC_URL: ${SPLUNK_HEC_URL}
      NGINX_STATUS: nginx:8080
    volumes:
      - ./otel/otel-conf.yml:/etc/otel/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: ["--config", "/etc/otel/config.yml"]
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}/{{.ID}}"
    hostname: otel_collector
    depends_on: 
      - nginx


  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonarqube
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      sonarqube_db:
        condition: service_healthy

  sonarqube_db:
    image: postgres:latest
    hostname: sonarqube_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube_db:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

  

volumes:
  jira_data:
  redis_data:

  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_db: