nodes = {
  "splunk"      => { ip: "192.168.1.31", hostname: "splunk.local" },
}

Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vm.box = "Ringworld/UbuntuServer"

  nodes.each do |name, opts|
    config.vm.define name do |node|
      node.vm.hostname = opts[:hostname]
      node.vm.network "public_network", ip: opts[:ip]
      
      node.vm.provision "file", source: ".env", destination:"/home/vagrant/.env" 
      node.vm.provision "shell", path: "./scripts/bootstrap.sh" 

    end
  end
end