- name: Run Prisma migrate deploy
  command: npx prisma migrate deploy
  args:
    chdir: "{{ app_dir }}"

- name: Run Prisma seed
  command: npx prisma db seed
  args:
    chdir: "{{ app_dir }}"

- name: Build the application
  command: npm run build
  args:
    chdir: "{{ app_dir }}"

- name: Start the application with PM2
  command: pm2 start npm --name jiraclone -- run start
  args:
    chdir: "{{ app_dir }}"
  notify: Save PM2 process list